module.exports = {
  content: ["./src/**/*.{html,ts,scss}"], // ← updated for Angular
  theme: {
    extend: {
      colors: {
        "brand-primary":  "var(--color-brand-primary)",
        "brand-primary-hover": "var(--color-brand-primary-hover)",
        "brand-accent":   "var(--color-brand-accent)",
        "brand-accent-hover": "var(--color-brand-accent-hover)",
        "bg-canvas":      "var(--color-bg-canvas)",
        "bg-surface":     "var(--color-bg-surface)",
        "bg-muted":       "var(--color-bg-muted)",
        "bg-inverse":     "var(--color-bg-inverse)",
        "border-default": "var(--color-border-default)",
        "border-strong":  "var(--color-border-strong)",
        "border-focus":   "var(--color-border-focus)",
        "status-success": "var(--color-status-success)",
        "status-success-bg": "var(--color-status-success-bg)",
        "status-success-text": "var(--color-status-success-text)",
        "status-warning": "var(--color-status-warning)",
        "status-error":   "var(--color-status-error)",
        "status-info":    "var(--color-status-info)",
      },
      textColor: {
        primary:   "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        muted:     "var(--color-text-muted)",
        inverse:   "var(--color-text-inverse)",
        accent:    "var(--color-text-accent)",
      },
      backgroundColor: {
        canvas:  "var(--color-bg-canvas)",
        surface: "var(--color-bg-surface)",
        muted:   "var(--color-bg-muted)",
        inverse: "var(--color-bg-inverse)",
      },
      borderColor: {
        default: "var(--color-border-default)",
        strong:  "var(--color-border-strong)",
        focus:   "var(--color-border-focus)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body:    ["var(--font-body)"],
        mono:    ["var(--font-mono)"],
      },
      borderRadius: {
        sm:   "var(--radius-sm)",
        md:   "var(--radius-md)",
        lg:   "var(--radius-lg)",
        xl:   "var(--radius-xl)",
        "2xl":"var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      spacing: {
        "0.5": "var(--space-0_5)",
        "1":   "var(--space-1)",
        "1.5": "var(--space-1_5)",
        "2":   "var(--space-2)",
        "3":   "var(--space-3)",
        "4":   "var(--space-4)",
        "5":   "var(--space-5)",
        "6":   "var(--space-6)",
        "8":   "var(--space-8)",
        "10":  "var(--space-10)",
        "12":  "var(--space-12)",
        "16":  "var(--space-16)",
        "20":  "var(--space-20)",
        "24":  "var(--space-24)",
      },
      boxShadow: {
        xs:    "var(--shadow-xs)",
        sm:    "var(--shadow-sm)",
        md:    "var(--shadow-md)",
        lg:    "var(--shadow-lg)",
        xl:    "var(--shadow-xl)",
        focus: "var(--shadow-focus)",
        brand: "var(--shadow-brand)",
      },
      transitionDuration: {
        fast:     "var(--duration-fast)",
        normal:   "var(--duration-normal)",
        moderate: "var(--duration-moderate)",
        slow:     "var(--duration-slow)",
      },
      zIndex: {
        base:     "var(--z-base)",
        raised:   "var(--z-raised)",
        dropdown: "var(--z-dropdown)",
        sticky:   "var(--z-sticky)",
        overlay:  "var(--z-overlay)",
        modal:    "var(--z-modal)",
        toast:    "var(--z-toast)",
        tooltip:  "var(--z-tooltip)",
      },
    },
  },
  plugins: [],
};
