import {
  HttpErrorResponse,
  HttpEvent,
  HttpHandlerFn,
  HttpInterceptorFn,
  HttpRequest,
  HttpResponse,
} from '@angular/common/http';
import { inject } from '@angular/core';
import { Observable, catchError, filter, switchMap, take, tap, throwError } from 'rxjs';
import { environment } from '../../../environments/environment';
import { SessionService } from '../../services/session.service';
type RequestType = 'GENERATE_SESSION' | 'LOGIN' | 'PUBLIC' | 'PROTECTED' | 'ASSET';
export const authInterceptor: HttpInterceptorFn = (
  req: HttpRequest<unknown>,
  next: HttpHandlerFn,
): Observable<HttpEvent<unknown>> => {
  const sessionService = inject(SessionService);
  const requestType = identifyRequestType(req.url);
  /*
   * Keep asset-based mock files untouched.
   */
  if (requestType === 'ASSET') {
    return next(req);
  }
  /*
   * Preserve mock URLs when mock API mode is enabled.
   */
  const finalUrl = environment.useMockApi ? req.url : resolveRealRequestUrl(req.url);

  /*
   * generateSessionToken must not send a previous token.
   */
  if (requestType === 'GENERATE_SESSION') {
    const sessionRequest = cloneWithHeaders(req, finalUrl, null);

    logRequest(sessionRequest, requestType);

    return next(sessionRequest).pipe(
      tap((event) => {
        captureRotatedToken(event, requestType, sessionService);
      }),

      catchError((error: HttpErrorResponse) => handleError(error, sessionService)),
    );
  }

  /*
   * /banking/web/login enters here.
   *
   * At this point it receives token A generated by
   * generateSessionToken.
   */
  const currentToken = sessionService.getAuthorizationToken();

  if (currentToken) {
    return forwardRequest(req, finalUrl, currentToken, requestType, next, sessionService);
  }

  /*
   * Public endpoints should not remain blocked waiting for a token.
   */
  if (requestType === 'PUBLIC' || environment.useMockApi) {
    const publicRequest = cloneWithHeaders(req, finalUrl, null);
    logRequest(publicRequest, requestType);
    return next(publicRequest).pipe(
      tap((event) => {
        captureRotatedToken(event, requestType, sessionService);
      }),
      catchError((error: HttpErrorResponse) => handleError(error, sessionService)),
    );
  }

  /*
   * A protected real request made while generateSessionToken is
   * still running waits until a non-null token becomes available.
   */
  console.log('[AuthInterceptor] Waiting for Authorization:', finalUrl);
  return sessionService.authorizationToken$.pipe(
    filter((token): token is string => Boolean(token)),
    take(1),
    switchMap((token) => forwardRequest(req, finalUrl, token, requestType, next, sessionService)),
    catchError((error: HttpErrorResponse) => handleError(error, sessionService)),
  );
};

function forwardRequest(
  req: HttpRequest<unknown>,
  finalUrl: string,
  token: string,
  requestType: RequestType,
  next: HttpHandlerFn,
  sessionService: SessionService,
): Observable<HttpEvent<unknown>> {
  const authenticatedRequest = cloneWithHeaders(req, finalUrl, token);
  logRequest(authenticatedRequest, requestType);
  return next(authenticatedRequest).pipe(
    /*
     * This tap runs before the response reaches AuthService or the
     * component subscriber.
     *
     * For LOGIN, token A is replaced by token B here.
     */
    tap((event) => {
      captureRotatedToken(event, requestType, sessionService);
    }),
    catchError((error: HttpErrorResponse) => handleError(error, sessionService)),
  );
}

function captureRotatedToken(
  event: HttpEvent<unknown>,
  requestType: RequestType,
  sessionService: SessionService,
): void {
  if (!(event instanceof HttpResponse)) {
    return;
  }
  const isTokenResponse = requestType === 'GENERATE_SESSION' || requestType === 'LOGIN';
  if (!isTokenResponse) {
    return;
  }
  /*
   * HttpHeaders lookup is case-insensitive.
   *
   * Add any actual alternate header names used by your gateway.
   */
  const freshToken =
    event.headers.get('Authorization') ??
    event.headers.get('X-Auth-Token') ??
    event.headers.get('JWT-Token');
  console.log('[AuthInterceptor] Token response received:', {
    requestType,
    responseUrl: event.url,
    exposedHeaders: event.headers.keys(),
    authorizationFound: Boolean(freshToken),
  });
  if (freshToken) {
    /*
     * GENERATE_SESSION:
     * Saves token A.
     *
     * LOGIN:
     * Immediately replaces token A with token B.
     */
    sessionService.setAuthorizationToken(freshToken);
    console.log(
      requestType === 'LOGIN'
        ? '[AuthInterceptor] Login JWT replaced successfully.'
        : '[AuthInterceptor] Session token stored successfully.',
    );
    return;
  }

  /*
   * A service-based mock may set the token directly because it does
   * not produce a real HttpResponse header.
   */
  if (environment.useMockApi) {
    console.log(
      `[AuthInterceptor] ${requestType} mock response contains no ` +
        'HTTP Authorization header. Mock service manages the token.',
    );
    return;
  }
  console.error(
    `[AuthInterceptor] ${requestType} returned no accessible ` + 'Authorization response header.',
  );
}

function cloneWithHeaders(
  req: HttpRequest<unknown>,
  finalUrl: string,
  token: string | null,
): HttpRequest<unknown> {
  let headers = req.headers
    .set('channelkey', 'WEB')
    .set('channelver', 'v1.0')
    .set('Accept-Language', 'en_US');
  if (!(req.body instanceof FormData) && !headers.has('Content-Type')) {
    headers = headers.set('Content-Type', 'application/json');
  }
  /*
   * Always overwrite Authorization with the latest token.
   *
   * Do not use:
   * if (!headers.has('Authorization'))
   *
   * That condition can preserve an older token already present
   * on the original request.
   */
  if (token) {
    headers = headers.set('Authorization', token);
  } else {
    headers = headers.delete('Authorization');
  }
  return req.clone({
    url: finalUrl,
    headers,
  });
}

function identifyRequestType(url: string): RequestType {
  const pathname = stripUrl(url).toLowerCase();
  if (pathname.startsWith('assets/') || pathname.includes('/assets/')) {
    return 'ASSET';
  }
  if (pathname.includes('generatesessiontoken')) {
    return 'GENERATE_SESSION';
  }

  /*
   * Explicitly matches your login endpoint:
   * /banking/web/login
   */
  if (
    pathname === '/banking/web/login' ||
    pathname.endsWith('/banking/web/login') ||
    pathname.endsWith('/login')
  ) {
    return 'LOGIN';
  }

  /*
   * Add any public endpoints that do not need Authorization.
   */
  if (pathname.endsWith('/health') || pathname.endsWith('/configuration')) {
    return 'PUBLIC';
  }
  return 'PROTECTED';
}

function stripUrl(url: string): string {
  try {
    /*
     * Supports absolute and relative URLs.
     */
    return new URL(url, window.location.origin).pathname;
  } catch {
    return url.split('?')[0].split('#')[0];
  }
}

function resolveRealRequestUrl(url: string): string {
  if (url.startsWith('http://') || url.startsWith('https://')) {
    return url;
  }
  if (url.startsWith('/TestBedGateway/')) {
    return url;
  }
  if (url.startsWith('/security/')) {
    return `/TestBedGateway/API${url}`;
  }
  const baseUrl = environment.apiBaseUrl.replace(/\/+$/, '');
  let path = url.startsWith('/') ? url : `/${url}`;
  if (baseUrl.endsWith('/banking') && path.startsWith('/banking/')) {
    path = path.slice(8);
  }
  return `${baseUrl}${path}`;
}

function logRequest(request: HttpRequest<unknown>, requestType: RequestType): void {
  const token = request.headers.get('Authorization');
  console.log('[AuthInterceptor] Outgoing request:', {
    requestType,
    url: request.url,
    channelkey: request.headers.get('channelkey'),
    channelver: request.headers.get('channelver'),
    authorizationPresent: Boolean(token),
    authorizationPreview: maskToken(token),
  });
}

function maskToken(token: string | null): string | null {
  if (!token) {
    return null;
  }
  if (token.length <= 12) {
    return '********';
  }
  return `${token.slice(0, 6)}...${token.slice(-4)}`;
}

function handleError(error: HttpErrorResponse, sessionService: SessionService): Observable<never> {
  if (error.status === 401) {
    sessionService.clearSession();
    console.warn('[AuthInterceptor] 401 received. Session cleared.');
  }
  return throwError(() => error);
}
